#!/usr/bin/env bash
# PreToolUse hook: reject Edit/Write/MultiEdit on app/gradle.lockfile.
#
# Test from a shell:
#   echo '{"tool_input":{"file_path":"app/gradle.lockfile"}}' \
#     | bash .claude/hooks/block-lockfile-edits.sh ; echo "exit=$?"
# Expected: exit=2 with the rejection message on stderr.
#   echo '{"tool_input":{"file_path":"app/build.gradle.kts"}}' \
#     | bash .claude/hooks/block-lockfile-edits.sh ; echo "exit=$?"
# Expected: exit=0, no output.
set -euo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | grep -oE '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | sed -E 's/.*"file_path"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/' || true)"

case "$file_path" in
    */app/gradle.lockfile|app/gradle.lockfile)
        cat >&2 <<MSG
Refusing to edit app/gradle.lockfile.

This file is regenerated by the Security CI workflow on every run via:
    ./gradlew --no-daemon :app:dependencies --write-locks

Manual edits drift the file from the resolved graph and silently break the
OSV-Scanner gate (it scans whatever lockfile is committed). If you really need
to change locked versions, change the version declarations in
gradle/libs.versions.toml and let the next CI run regenerate the lockfile.
MSG
        exit 2
        ;;
esac

exit 0
