version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      gradle-minor-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - gradle

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - github-actions
